export const normal = 'normal'
export const focused = 'focused'
export const changed = 'changed'
export const disabled = 'disabled'
export const error = 'error'
export const warning = 'warning'
export const success = 'success'